### ISSUE TITLE
Clarifications on Abbreviations

### ISSUE THREAD

**Issue by RAbraham** [guitarvydas/py0d#1]
What's EH 
py0d/eh.py

Down: From parent to child?
Across: Child to Child
Up: Child to Parent?

**Comment by guitarvydas** [comment]
diagrams added to README.md to clarify Down/Across/Up routing

**Comment by guitarvydas** [comment]
added discussion about the name to README.md

**Comment by RAbraham** [comment]
Oh, if EH is 'eh', then perhaps using 'Eh' as EH made me think it's an abbreviation but this is minor feedback. anything works.
